apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kafka-to-web
spec:
  template:
    spec:
      containers:
        - image: gcr.io/none-219021/spring-kafka-to-web
          env:
            - name: BOOTSTRAP_SERVER
              value: my-cluster-kafka-bootstrap:9092
            - name: KAFKA_TOPIC
              value: stackoverflow-questions